on: push
name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂  Heaven MP eCommerce (WN)
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 190.104.236.50
        username: lucas@heaven.com.ar
        password: ${{ secrets.PASS }}
        server-dir: mp-ecommerce/
        exclude: .git*
          - .git*/**
          - **/.git*/**
